const envConstants = {
    PORT: 5000,
    NODE_ENV: 'development',
    MONGO_URI: 'mongodb://localhost:27017/Server',
    ACCESS_TOKEN_SECRET: "youraccesstokensecret",
    REFRESH_TOKEN_SECRET: "yourrefreshtokensecret",
    FRONTEND_URL: "http://localhost:3000",
    SMTP_HOST: "localhost",
    SMTP_PORT: 587,
    SMTP_USER: "username",
    SMTP_PASS: "pass",
    SENDING_USER: "Server <user>",
    MAIL_FROM: "noreply@example.com",
    BREVO_API_KEY: "",
    GOOGLE_CLIENT_ID: "",
    GOOGLE_CLIENT_SECRET: "",
    GOOGLE_REDIRECT_URI: "http://localhost:5000/api/auth/google/callback",
    SEND_MAIL: false,
    REDIS_URL: "",
    REDIS_HOST: "127.0.0.1",
    REDIS_PORT: 6379,
    REDIS_PASSWORD: "",
} as const;

export default envConstants;
