const TIMELINE_TYPES = [
  "AUCTION_CREATED",
  "AUCTION_STARTED",
  "BID_PLACED",
  "NEW_HIGHEST_BID",
  "AUCTION_ENDED",
  "WINNER_DECLARED",
  "PAYMENT_COMPLETED",
] as const;

export default TIMELINE_TYPES;